# Pick a target and energy that KDUQ should be fit to, and see if our prior looks somewhat similar

In [1]:
import numpy as np

In [2]:
neutron = (1, 0)
proton = (1, 1)

In [3]:
from jitr.reactions import ElasticReaction

In [4]:
from jitr.optical_potentials import kduq

In [5]:
kduq_samples = kduq.get_samples_federal(neutron)

In [6]:
import pickle

import elm

with open("./prior_distribution.pickle", "rb") as f:
    prior = pickle.load(f)
prior_samples = elm.elm.array_to_list(prior.rvs(10000))

Using database version X4-2024-12-31 located in: /home/beyerk/db/exfor/unpack_exfor-2024/X4-2024-12-31


In [7]:
target = (40, 20)
energy_lab = 35
rxn = ElasticReaction(target=target, projectile=neutron)
rxn.target.Efn

-11.998996893828007

In [8]:
kinematics = rxn.kinematics(energy_lab)
kinematics

ChannelKinematics(Elab=35, Ecm=34.1381096190068, mu=948.456319831029, k=1.2782522662832476, eta=0.0)

In [9]:
elm_prior_params = [
    elm.elm.calculate_parameters(neutron, target, kinematics.Ecm, rxn.target.Efn, p)
    for p in prior_samples
]

In [10]:
isoscalar, isovector, so0, so1, coul,asym =  (np.array(l) for l in zip(*elm_prior_params))

In [11]:
kduq_params = [
    kduq.calculate_params(neutron, target, kinematics.Elab, p)
    for p in kduq_samples
]

/home/beyerk/Projects/jitr/src/jitr/optical_potentials/kduq.py:332: RuntimeWarning: overflow encountered in exp
  1 + np.exp((A - params["d2_A3"]) / params["d2_A2"])


In [12]:
kduq_coul, kduq_central, kduq_so  =  (np.array(l) for l in zip(*kduq_params))

In [25]:
np.mean(kduq_central,axis=0)

array([43.3536897 ,  3.98116843,  0.67744189,  3.76970208,  3.98116843,
        0.67744189,  4.9272036 ,  4.42616682,  0.56072929])

In [13]:
np.mean(isoscalar,axis=0)

array([39.57234548,  5.09848759,  7.87790031,  3.90436987,  0.7299312 ,
        3.90436987,  0.7299312 ])

In [14]:
np.mean(isovector,axis=0)

array([9.72135154e+00, 1.99147684e-02, 2.01130609e+01, 3.90261501e+00,
       7.30342400e-01, 3.90261501e+00, 7.30342400e-01])

In [27]:
np.mean(kduq_so,axis=0)

array([ 4.13747859,  3.48486319,  0.57430756, -0.13998511,  3.48486319,
        0.57430756])

In [15]:
np.mean(so0,axis=0)

array([-8.70591601, -1.12166727,  3.90436987,  0.7299312 ])

In [16]:
np.mean(so1,axis=0)

array([-2.13869734, -0.00438125,  3.90436987,  0.7299312 ])

In [17]:
np.mean(coul,axis=0)

array([20.        ,  3.90436987])

In [18]:
np.mean(asym,axis=0)

0.0

In [19]:
np.std(isoscalar,axis=0)

array([1.99662366, 2.58755011, 2.76518265, 0.16165183, 0.02500193,
       0.16165183, 0.02500193])

In [20]:
np.std(isovector,axis=0)

array([4.32079475, 3.36451482, 7.82114228, 0.16144514, 0.02499479,
       0.16144514, 0.02499479])

In [21]:
np.std(so0,axis=0)

array([0.4392572 , 0.56926103, 0.16165183, 0.02500193])

In [22]:
np.std(so1,axis=0)

array([0.95057485, 0.74019326, 0.16165183, 0.02500193])

In [23]:
np.std(coul,axis=0)

array([0.        , 0.16165183])

In [24]:
np.std(asym,axis=0)

0.0