# Pick a target and energy that KDUQ should be fit to, and see if our prior looks somewhat similar

In [19]:
import numpy as np

In [1]:
neutron = (1, 0)
proton = (1, 1)

In [2]:
from jitr.reactions import ElasticReaction

In [3]:
from jitr.optical_potentials import kduq

In [4]:
kduq_samples = kduq.get_samples_federal(neutron)

In [5]:
import pickle

import elm

with open("./prior_distribution.pickle", "rb") as f:
    prior = pickle.load(f)
prior_samples = elm.elm.array_to_list(prior.rvs(1000))

Using database version X4-2024-12-31 located in: /home/beyerk/db/exfor/unpack_exfor-2024/X4-2024-12-31


In [6]:
target = (40, 20)
energy_lab = 35
rxn = ElasticReaction(target=target, projectile=neutron)
rxn.target.Efn

-11.998996893828007

In [7]:
kinematics = rxn.kinematics(energy_lab)
kinematics

ChannelKinematics(Elab=35, Ecm=34.1381096190068, mu=948.456319831029, k=1.2782522662832476, eta=0.0)

In [8]:
elm_prior_params = [
    elm.elm.calculate_parameters(neutron, target, kinematics.Ecm, rxn.target.Efn, p)
    for p in prior_samples
]

In [20]:
isoscalar, isovector,so,coul,asym =  (np.array(l) for l in zip(*elm_prior_params))

In [23]:
np.mean(isoscalar,axis=0)

array([39.58745548,  5.05691076,  7.93186878,  3.8928841 ,  0.72905605,
        3.8928841 ,  0.72905605])

In [24]:
np.mean(isovector,axis=0)

array([-2.69908545,  0.05416926, 20.35695407,  3.90622363,  0.72943866,
        3.90622363,  0.72943866])

In [25]:
np.mean(so,axis=0)

array([5.58      , 3.8928841 , 0.72905605])

In [26]:
np.mean(coul,axis=0)

array([20.       ,  3.8928841])

In [27]:
np.mean(asym,axis=0)

0.0

In [29]:
np.std(isoscalar,axis=0)

array([2.06412352, 2.52571048, 2.69731622, 0.1628371 , 0.02617708,
       0.1628371 , 0.02617708])

In [30]:
np.std(isovector,axis=0)

array([6.01930734, 3.31289036, 7.77749106, 0.16475468, 0.02510764,
       0.16475468, 0.02510764])

In [31]:
np.std(so,axis=0)

array([5.59552404e-14, 1.62837102e-01, 2.61770758e-02])

In [32]:
np.std(coul,axis=0)

array([0.       , 0.1628371])

In [33]:
np.std(asym,axis=0)

0.0