# Set up `Observation` objects for each Exfor subentry

Internally, this involves initializing a `jitr.xs.elastic.DifferentialWorkspace` for each `Observation`, which precomputes things like boundary conditions to speed up computation of observables for an interaction parameter.

In [1]:
import numpy as np

In [2]:
import rxmc

Using database version X4-2024-12-31 located in: /home/beyerk/db/exfor/unpack_exfor-2024/X4-2024-12-31


In [3]:
import lzma
import pickle
from pathlib import Path

from tqdm import tqdm

output_dir = Path("./data/")

In [4]:
with lzma.open(output_dir / "pp_elastic_data.xz", "rb") as f:
    pp_elastic_measurements = pickle.load(f)
with lzma.open(output_dir / "nn_elastic_data.xz", "rb") as f:
    nn_elastic_measurements = pickle.load(f)

In [7]:
for entry_id, mlist in pp_elastic_measurements.items():
    for rxn, m in mlist:
        print(m.systematic_norm_err)


[0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05
 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05]
[0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05
 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05
 0.05 0.05]
[0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05
 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05]
[0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05
 0.05 0.05 0.05 0.05 0.05 0.05 0.05 0.05]
[0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03
 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03
 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03
 0.03 0.03 0.03 0.03 0.03 0.03]
[0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03
 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03
 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03
 0.03 0.03 0.03 0.03 0.0

In [5]:
nn_observations = {}
for entry_id, mlist in tqdm(nn_elastic_measurements.items()):
    if entry_id not in nn_observations:
        nn_observations[entry_id] = []
    for rxn, m in mlist:
        nn_observations[entry_id].append(
            rxmc.elastic_diffxs_observation.ElasticDifferentialXSObservation(
                measurement=m,
                reaction=rxn,
                quantity="dXS/dA",
                lmax=50,
                angles_vis=np.linspace(
                    max(0, np.min(m.x) * 0.9), min(180, np.max(m.x) * 1.1), 100
                ),
                ObservationClass=rxmc.observation.Observation,
                error_kwargs={
                    "include_sys_norm_err": True,
                    "include_sys_offset_err": True,
                },
            )
        )

  0%|                                                                                                                                                           | 0/18 [00:00<?, ?it/s]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])]


  6%|████████▏                                                                                                                                          | 1/18 [00:08<02:19,  8.22s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])]


 11%|████████████████▎                                                                                                                                  | 2/18 [00:11<01:29,  5.58s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])]


 17%|████████████████████████▌                                                                                                                          | 3/18 [00:15<01:11,  4.79s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])]
[0.02864583 0.0376569  0.04132231 0.04568528 0.04615385 0.05820106
 0.0707635  0.23390558] [array([False, False, False, False, False, False,  True, False]), array([False,  True, False, False, False, False, False, False]), array([False, False, False, False, False,  True, False, False]), array([False, False,  True, False, False, False, False, False]), array([False, False, False,  True, False, False, False, False]), array([False, False, False, False,  True, False, False, False]), array([False, False, False, False, False, False, False,  True]), array([ True, False, False, False, False, False, False, False])]
[0.02727273 0.02848101 0.05432596 0.05725191 0.06115108 0.0619469
 0.0781759  0.24429224] [array([False, False, False, False,  True, False, False, False]), array([False

 22%|████████████████████████████████▋                                                                                                                  | 4/18 [00:58<04:37, 19.80s/it]

[0.08461538 0.1275     0.13191489 0.14893617 0.18803419 0.24444444
 0.28314607] [array([False, False, False, False, False,  True, False]), array([False, False, False, False, False, False,  True]), array([False, False, False,  True, False, False, False]), array([False,  True, False, False, False, False, False]), array([False, False,  True, False, False, False, False]), array([False, False, False, False,  True, False, False]), array([ True, False, False, False, False, False, False])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])]


 28%|████████████████████████████████████████▊                                                                                                          | 5/18 [01:04<03:11, 14.75s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  Tr

 33%|█████████████████████████████████████████████████                                                                                                  | 6/18 [01:16<02:45, 13.76s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])]
[0.035 0.035] [array([ True,  True,  True,  True, False,  True,  True, False, False,
       False,  True,  True,  True,  True, False, False,  True, False,
       False, False, False, False, False, False, False,  True, False]), array([False, False, False, False,  True, False, False,  True,  True,
        True, False, False, False, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True])]
[0.035 0.035] [array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True, False, False,  True,  True,
        True,  True, False, False, False,  True,  True, False,  True,
        True]), array([False,  True, False,  True, False,  T

 39%|█████████████████████████████████████████████████████████▏                                                                                         | 7/18 [01:22<02:03, 11.19s/it]

[0.035 0.035] [array([ True, False,  True, False, False,  True, False, False, False,
       False,  True,  True,  True,  True, False, False, False, False,
        True,  True,  True, False, False, False,  True, False]), array([False,  True, False,  True,  True, False,  True,  True,  True,
        True, False, False, False, False,  True,  True,  True,  True,
       False, False, False,  True,  True,  True, False,  True])]
[0.05 0.05] [array([False, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
        True,  True,  True, False,  True,  True, False, False,  True]), array([ True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False, False, False,  True, False, False,  True,  True, False])]
[0.05 0.05] [array([False, False,  True, False,  True,  True, False, False, False,
        True,  True,  True, False, False, False,  True,

 44%|█████████████████████████████████████████████████████████████████▎                                                                                 | 8/18 [01:28<01:35,  9.54s/it]

[0.05 0.05] [array([False, False,  True, False,  True,  True,  True, False, False,
       False,  True,  True, False,  True, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
       False, False]), array([ True,  True, False,  True, False, False, False,  True,  True,
        True, False, False,  True, False,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])]
[0.05] [array([ Tr

 50%|█████████████████████████████████████████████████████████████████████████▌                                                                         | 9/18 [01:44<01:44, 11.56s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])]


 56%|█████████████████████████████████████████████████████████████████████████████████                                                                 | 10/18 [01:50<01:18,  9.83s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])]


 61%|█████████████████████████████████████████████████████████████████████████████████████████▏                                                        | 11/18 [01:54<00:56,  8.05s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])]


 67%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                                | 12/18 [01:56<00:37,  6.26s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])]


 72%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                        | 13/18 [02:02<00:31,  6.30s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])]


 78%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                | 14/18 [02:09<00:25,  6.38s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])]


 83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 15/18 [02:13<00:17,  5.73s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])]
[0.026 0.026 0.026] [array([False, False,  True, False, False, False, False,  True, False,
        True, False,  True,  True,  True, False, False,  True, False,
       False, False,  True, False, False,  True, False, False,  True,
       False,  True,  True, False, False, False, False]), array([ True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True, False, False, False, False,  True, False,  True,
        True,  True, False,  True,  True, False,  True,  True, False,
        True, False, False,  True,  True,  True,  True]), array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False,

 89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 16/18 [02:18<00:10,  5.43s/it]

[0.026 0.026 0.026] [array([False,  True,  True,  True, False, False,  True,  True, False,
        True,  True, False, False, False, False,  True,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
       False,  True, False, False, False, False, False]), array([ True, False, False, False,  True,  True, False, False,  True,
       False, False,  True,  True,  True, False, False, False,  True,
       False, False, False, False, False,  True,  True, False, False,
        True, False,  True,  True,  True,  True,  True]), array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])]


 94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 17/18 [02:21<00:04,  4.66s/it]

[0.03 0.03 0.03] [array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False]), array([False, False,  True, False, False,  True,  True,  True, False,
        True, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True, False,  True]), array([False, False, False,  True,  True, False, False, False,  True,
       False,  True,  True, False, False,  True, False, False, False,
       False, False, False,  True, False])]


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [02:23<00:00,  8.00s/it]

[0.00968656 0.01308466 0.02414906 0.02699112 0.03431245 0.0440994
 0.05035871 0.05346275 0.05562756 0.06806159 0.06844531 0.08257122
 0.08884979 0.09280602 0.11324673 0.11511997 0.13675959 0.13842796
 0.14137938 0.14298309 0.14718117 0.15312306 0.16588395 0.17153354
 0.20008998 0.20546191 0.28577728 0.40564037 0.48497015] [array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False]), array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False]), array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,

In [6]:
pp_observations = {}
for entry_id, mlist in tqdm(pp_elastic_measurements.items()):
    if entry_id not in pp_observations:
        pp_observations[entry_id] = []
    for rxn, m in mlist:
        pp_observations[entry_id].append(
            rxmc.elastic_diffxs_observation.ElasticDifferentialXSObservation(
                m,
                rxn,
                "dXS/dRuth",
                50,
                angles_vis=np.linspace(
                    max(0, np.min(m.x) * 0.9), min(180, np.max(m.x) * 1.1), 100
                ),
                ObservationClass=rxmc.observation.Observation,
                error_kwargs={
                    "include_sys_norm_err": True,
                    "include_sys_offset_err": True,
                },
            )
        )

  0%|                                                                                                                                                           | 0/48 [00:00<?, ?it/s]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])]


  2%|███                                                                                                                                                | 1/48 [00:06<05:15,  6.71s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])]


  4%|██████▏                                                                                                                                            | 2/48 [00:08<02:58,  3.88s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])]
[0.03 0.03 0.03 0.03] [array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False]), array([False,  True, False,  True, False,  True, False,  True, False,
       False, False,  True, False,  True,  True, False, False, False,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True, False,
        True,  True,  True,  True,  True, False, False, False, False,
        True,  True, False]), array([ True, False,  True, Fals

  6%|█████████▏                                                                                                                                         | 3/48 [00:43<13:33, 18.07s/it]

[0.03 0.03 0.03 0.03] [array([False, False, False, False, False, False, False,  True, False,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
       False, False, False]), array([ True,  True,  True,  True, False,  True,  True, False, False,
       False, False, False,  True, False, False,  True,  True,  True,
        True,  True, False,  True, False, False,  True,  True, False,
        True, False,  True, False, False,  True, False,  True, False,
       False,  True,  True,  True, False, False, False,  True,  True,
        True,  True, False]), array([False, False, False, False,  True, False, False, False,  True,
       False, False,  True, False,  True,  True, False, False, False,
       False, False,  True, False,  True, False, False, False,  True,
       

  8%|████████████▎                                                                                                                                      | 4/48 [00:55<11:23, 15.54s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])]


 10%|███████████████▎                                                                                                                                   | 5/48 [00:59<08:10, 11.40s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  Tr

 12%|██████████████████▍                                                                                                                                | 6/48 [01:13<08:39, 12.37s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])]


 15%|█████████████████████▍                                                                                                                             | 7/48 [01:15<06:07,  8.97s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])]


 17%|████████████████████████▌                                                                                                                          | 8/48 [01:17<04:35,  6.89s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])]


 19%|███████████████████████████▌                                                                                                                       | 9/48 [01:21<03:51,  5.95s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])]


 21%|██████████████████████████████▍                                                                                                                   | 10/48 [01:29<04:05,  6.45s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])]
[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])]


 23%|█████████████████████████████████▍                                                                                                                | 11/48 [01:40<04:55,  7.98s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])]
[0.03 0.03 0.03 0.03] [array([False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False]), array([False,  True,  True, False, False,  True,  True, False, False,
      

 25%|████████████████████████████████████▌                                                                                                             | 12/48 [01:47<04:31,  7.54s/it]

[0.01 0.01] [array([False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False]), array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
     

 27%|███████████████████████████████████████▌                                                                                                          | 13/48 [01:53<04:11,  7.19s/it]

[0.05 0.05 0.05] [array([False, False, False, False, False,  True,  True,  True, False,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
        True, False, False,  True, False,  True,  True, False, False,
       False,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True, False,
       False, False]), array([ True,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
       False,  True,  True, False,  True, False, False,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True, False, False, False,  True,  True, 

 29%|██████████████████████████████████████████▌                                                                                                       | 14/48 [01:55<03:12,  5.66s/it]

[0.05] [array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])]
[0.1 0.1 0.1] [array([False, False, False, False, False,  True,  True, False, False,
        True, False,  True,  True, False, False, False, False, False,
        True, False, False, False,  True, False,  True,  True, False,
       False,  True,  True,  True, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False]), array([ True,  True,  True,  True,  True, False, False,  True,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False, False, False,  True,
        True, False, False, False,  True, False,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True]), array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False

 29%|██████████████████████████████████████████▌                                                                                                       | 14/48 [02:21<05:42, 10.08s/it]


KeyboardInterrupt: 

In [ ]:
with lzma.open(output_dir / "pp_elastic_observations.xz", "wb") as f:
    pickle.dump(pp_observations, f)
with lzma.open(output_dir / "nn_elastic_observations.xz", "wb") as f:
    pickle.dump(nn_observations, f)

## Some tests

In [ ]:
with open("../likelihood_model/likelihood_model.pkl", "rb") as f:
    lm = pickle.load(f)

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
pp_observations.keys()

In [ ]:
obs = pp_observations["D0289"][0]
meas = pp_elastic_measurements["D0289"][0][1]

In [ ]:
y = 0.9 * obs.y + 0.01

In [ ]:
plt.errorbar(
    obs.x,
    obs.y,
    np.diag(np.sqrt(obs._obs.statistical_covariance)),
    linestyle="none",
    marker="o",
)
plt.plot(obs.x, y)
# plt.yscale("log")

In [ ]:
np.sum((y - obs.y) ** 2 / ((y * 0.3) ** 2 + np.diag(obs._obs.statistical_covariance)))

In [ ]:
N = obs.compute_normalization(meas)

In [ ]:
lm.chi2(obs, y)

In [ ]:
r = y - obs.y
Sigma = (
    meas.systematic_norm_err ** 2 * np.outer(y, y)
    + np.diag( (meas.statistical_err / N )  ** 2)
    + np.diag((y * lm.fractional_uncorrelated_error) ** 2)
)

r.T @ np.linalg.inv(Sigma) @ r

In [ ]:
(meas.statistical_err / N )  ** 2 - np.diag(obs._obs.statistical_covariance)

In [ ]:
obs._obs.systematic_normalization_covariance[0,:]